# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatBot(object):
    def setupUi(self, ChatBot):
        ChatBot.setObjectName("ChatBot")
        ChatBot.resize(431, 518)
        ChatBot.setMaximumSize(QtCore.QSize(431, 518))
        ChatBot.setBaseSize(QtCore.QSize(400, 600))
        ChatBot.setStyleSheet("QMainWindow{\n"
"background:rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ChatBot)
        self.centralwidget.setObjectName("centralwidget")
        self.recordButton = QtWidgets.QPushButton(self.centralwidget)
        self.recordButton.setGeometry(QtCore.QRect(10, 460, 41, 41))
        self.recordButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.recordButton.setMouseTracking(True)
        self.recordButton.setToolTipDuration(1500)
        self.recordButton.setStyleSheet("QPushButton{\n"
"    background: none;\n"
"    border:none;\n"
"    border-radius:20%\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(166, 200, 255)\n"
"}")
        self.recordButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Icon/recordVoice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recordButton.setIcon(icon)
        self.recordButton.setIconSize(QtCore.QSize(40, 40))
        self.recordButton.setObjectName("recordButton")
        self.chatBox = QtWidgets.QTextEdit(self.centralwidget)
        self.chatBox.setGeometry(QtCore.QRect(60, 460, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.chatBox.setFont(font)
        self.chatBox.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.chatBox.setStyleSheet("QTextEdit{\n"
"border: none;\n"
"border-radius: 20px;\n"
"corlor: rgb(209, 209, 209);\n"
"background: rgb(208, 208, 208);\n"
"padding-top:7%;\n"
"padding-left:10px;\n"
"font-size:10pt;\n"
"padding-right:15px;\n"
"padding-bottom:7%\n"
"}")
        self.chatBox.setLocale(QtCore.QLocale(QtCore.QLocale.Vietnamese, QtCore.QLocale.Vietnam))
        self.chatBox.setLineWidth(2)
        self.chatBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chatBox.setPlaceholderText("")
        self.chatBox.setObjectName("chatBox")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(380, 460, 41, 41))
        self.sendButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendButton.setMouseTracking(True)
        self.sendButton.setToolTipDuration(1500)
        self.sendButton.setStyleSheet("QPushButton{\n"
"    background: none;\n"
"    border:none;\n"
"    border-radius:20%\n"
"}\n"
"QPushButton:Hover{\n"
"    background: rgb(160, 196, 255);\n"
"}")
        self.sendButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./Icon/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendButton.setIcon(icon1)
        self.sendButton.setIconSize(QtCore.QSize(55, 53))
        self.sendButton.setObjectName("sendButton")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 10, 411, 431))
        self.listView.setAutoFillBackground(True)
        self.listView.setStyleSheet("QListView{\n"
"border:none;\n"
"}")
        self.listView.setObjectName("listView")
        ChatBot.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChatBot)
        QtCore.QMetaObject.connectSlotsByName(ChatBot)

    def retranslateUi(self, ChatBot):
        _translate = QtCore.QCoreApplication.translate
        ChatBot.setWindowTitle(_translate("ChatBot", "ChatBot"))
        self.recordButton.setToolTip(_translate("ChatBot", "Chat bằng giọng nói"))
        self.chatBox.setHtml(_translate("ChatBot", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:5px; margin-bottom:0px; margin-left:10px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9.5pt;\"><br /></p></body></html>"))
        self.sendButton.setToolTip(_translate("ChatBot", "Gửi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChatBot = QtWidgets.QMainWindow()
    ui = Ui_ChatBot()
    ui.setupUi(ChatBot)
    ChatBot.show()
    sys.exit(app.exec_())